BlogSite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("project.urls")),
    path("", include("users.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from project.views import home_view, post_create_view, post_detail_view , post_list_view, post_delete_view, post_modify_view, create_comment_view

app_name = "project"
urlpatterns = [
    path("", home_view, name="home"),
    path("post/<int:pk>/", post_detail_view, name="posts"),
    path("create/post/", post_create_view, name="post-create"),
    path("post/", post_list_view, name="post-list"),
    path("post/<int:pk>/delete/", post_delete_view , name= "post-delete" ),
    path("post/<int:pk>/modify/", post_modify_view , name= "post-modify" ),
    path("post/add/comment/", create_comment_view, name="comment-create")
]

users/urls.py
from django.urls import path

from users.views import login_view, logout_view

app_name = "users"

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout")
]

project/models.py
from django.db import models
from django.urls import reverse
from users.models import User

# from django.forms import ModelChoiceField

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to="project/post_thumbnail/")
    category = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    body = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at =models.DateTimeField(auto_now=True)




    def __str__(self):
        return self.title
    
    
    
    def get_absolute_url(self):
        return reverse("project:posts", kwargs={"pk": self.pk})
        

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

users/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext as _

class User(AbstractUser):
    avatar = models.ImageField(upload_to="users/avatars/",
                               default="users/avatars/default_user_avatar.png",
                               blank=True,
                               verbose_name=_("Avatar")
                               )


# Create your models here.
class Meta:
    verbose_name = _("User")
    verbose_name_plural = _("Users")

project/forms.py
from this import d
from tkinter import Widget
from django import forms
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect

from users.models import User
from project.models import Post, Comment


class PostCreateFrom(forms.ModelForm):
    

    def save(self, user: User, commit: bool = False):
        post = super().save(False) 


        post.user = user

        if commit:
            post.save()  

    class Meta:
        model = Post
        exclude = ["user"]

class PostModifyFrom(forms.ModelForm):

    class Meta:
        model = Post
        exclude = ["user"]
    
class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [ "post" ,"body"]
        Widget = {
            "post" : forms.HiddenInput
        }

users/forms.py
from django import forms

from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm

from users.models import User

class UserLoginForm(forms.ModelForm):
    username = forms.CharField(max_length=255)


    class Meta:
        model = User
        fields = [ "password"]
        widgets ={
            "password" : forms.PasswordInput()
        }

      

project/views.py
from tkinter.tix import Form
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from project.forms import PostCreateFrom, PostModifyFrom, CommentCreateForm
from project.models import Post, Comment
from django.contrib.auth.decorators import login_required

def home_view(request: HttpRequest) -> HttpResponse:
    return render(request, "index.html",{
        "post_list" : Post.objects.order_by("-created_at").all() ,
        "post_form" : PostCreateFrom() 

    })
def post_list_view(request: HttpRequest, ) -> HttpResponse:
    return render(request, "post.html",{
        "post_list": Post.objects.all()
    })

def post_detail_view(request: HttpRequest, pk: int) -> HttpResponse:
    return render (request, "post.html",{
        "post" : get_object_or_404(Post, pk=pk),
        "comments" : Comment.objects.filter(post__pk=pk),
        "comment_form" : CommentCreateForm()

    }) 

@login_required   
def post_create_view(request: HttpRequest, ) ->HttpResponse:
    
    if request.method != "POST" :
        return redirect("project:home")
    
    form = PostCreateFrom(request.POST, request.FILES)
    

    if form.is_valid():
        post = form.save(request.user, True)
        return redirect("project:posts", post.pk)
    # print(form.errors)    
    return redirect("project:home")    


@login_required
def post_delete_view(request: HttpRequest, pk :int) -> HttpResponse:
    post =get_object_or_404(Post, pk=pk)

    if request.user != post.user:
        return redirect("project:home")
    post.delete()
    return redirect("project:home")


@login_required
def post_modify_view(request: HttpRequest, pk :int) -> HttpResponse:
    post =get_object_or_404(Post, pk=pk)

    if request.user != post.user:
        return redirect("project:home")
    form = PostModifyFrom(instance=post)

    if request.method == "POST" :
        form = PostCreateFrom(request.POST, request.FILES)
    

        if form.is_valid():
            form.save( True)
        
    return  redirect(request, "post-edit.html",{
        "post_form" : form
    })

@login_required
def create_comment_view(request: HttpRequest)-> HttpResponse:
    if request.method == "GET":
        return redirect("project:home")


    form = CommentCreateForm(request.POST)
    post_pk = request.POST.get("post")
    get_object_or_404(Post, pk=post_pk)

    if form.is_valid():
        comment = form.save(comit=False)
        comment.user = request.user
        comment.save()
        return redirect("project:posts", post_pk )

    return render (request, "post.html",{
        "post" : get_object_or_404(Post, pk=post_pk),
        "comments" : Comment.objects.filter(post__pk=post_pk),
        "comment_form" : form

        
    })    

users/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render

from users.forms import UserLoginForm
from django.contrib.auth import authenticate
from users.models import User
from django.contrib.auth import login as auth_login , logout as auth_logout
# Create your views here.

def login_view(request : HttpRequest) -> HttpResponse:
    if request.user.is_authenticated:
        return redirect("project:home")
    form = UserLoginForm()

    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data["username"], password=form.cleaned_data["password"])
            if user:
                auth_login(request, user)
                return redirect("projcet:home")
            form.add_error("password", "check password")    

            



    return render(request, "auth/login.html", {
        "form" : form
    })

def logout_view(request : HttpRequest) -> HttpResponse: 
    auth_logout(request)
    return redirect("project:home")

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Xtra Blog</title>
	<link rel="stylesheet" href="fontawesome/css/all.min.css"> <!-- https://fontawesome.com/ -->
	<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"> <!-- https://fonts.google.com/ -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/templatemo-xtra-blog.css" rel="stylesheet">
<!--
    
TemplateMo 553 Xtra Blog

https://templatemo.com/tm-553-xtra-blog

-->
</head>
<body>
	<header class="tm-header" id="tm-header">
        <div class="tm-header-wrapper">
            <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="tm-site-header">
                <div class="mb-3 mx-auto tm-site-logo"><i class="fas fa-times fa-2x"></i></div>            
                <h1 class="text-center">Xtra Blog</h1>
            </div>
            <nav class="tm-nav" id="tm-nav">            
                <ul>
                    <li class="tm-nav-item"><a href="index.html" class="tm-nav-link">
                        <i class="fas fa-home"></i>
                        Blog Home
                    </a></li>
                    <li class="tm-nav-item"><a href="{% url 'projcet: post-create' %}" class="tm-nav-link">
                        <i class="fas fa-pen"></i>
                        post-create
                    </a></li>
                    <li class="tm-nav-item active"><a href="about.html" class="tm-nav-link">
                        <i class="fas fa-users"></i>
                        About Xtra
                    </a></li>
                    <li class="tm-nav-item"><a href="contact.html" class="tm-nav-link">
                        <i class="far fa-comments"></i>
                        Contact Us
                    </a></li>
                </ul>
            </nav>
            <div class="tm-mb-65">
                <a href="https://facebook.com" class="tm-social-link">
                    <i class="fab fa-facebook tm-social-icon"></i>
                </a>
                <a href="https://twitter.com" class="tm-social-link">
                    <i class="fab fa-twitter tm-social-icon"></i>
                </a>
                <a href="https://instagram.com" class="tm-social-link">
                    <i class="fab fa-instagram tm-social-icon"></i>
                </a>
                <a href="https://linkedin.com" class="tm-social-link">
                    <i class="fab fa-linkedin tm-social-icon"></i>
                </a>
            </div>
            <p class="tm-mb-80 pr-5 text-white">
                Xtra Blog is a multi-purpose HTML template from TemplateMo website. Left side is a sticky menu bar. Right side content will scroll up and down.
            </p>
        </div>
    </header>
    <div class="container-fluid">
        <main class="tm-main">
            <!-- Search form -->
            <div class="row tm-row">
                <div class="col-12">
                    <form method="GET" class="form-inline tm-mb-80 tm-search-form">                
                        <input class="form-control tm-search-input" name="query" type="text" placeholder="Search..." aria-label="Search">
                        <button class="tm-search-button" type="submit">
                            <i class="fas fa-search tm-search-icon" aria-hidden="true"></i>
                        </button>                                
                    </form>
                </div>                
            </div>            
            <div class="row tm-row tm-mb-45">
                <div class="col-12">
                    <hr class="tm-hr-primary tm-mb-55">
                    <img src="img/about-01.jpg" alt="Image" class="img-fluid">
                </div>
            </div>
            <div class="row tm-row tm-mb-40">
                <div class="col-12">                    
                    <div class="mb-4">
                        <h2 class="pt-2 tm-mb-40 tm-color-primary tm-post-title">About this xtra blog</h2>
                        <p>
                            You can immediately download 
                                <a rel="nofollow" href="https://templatemo.com/tm-553-xtra-blog" target="_blank">Xtra Blog Template</a> 
                                from TemplateMo website for 100% free of charge. Etiam vehicula, tortor ac eleifend tincidunt, diam neque pellentesque ipsum, 
                                a geugiat eros mauris eget lorem. Quisque in
                            bibendum elit, in egestas turpis. Vestibulum ornare sollicitudin congue. Aliquam lorem mi, maximus at iaculis ut, viverra vel
                            mauris. Duis congue luctus metus, sodales tincidunt lectus fringilla ut. Nunc tempus at magna sed vestibulum.
                        </p>
                        <p>
                            Proin et arcu ligula. Praesent quis erat eu est solliditudin tristique ut in arcu. Donec bibendum ex id ligula semper dictum.
                            Proin malesuada luctus auctor. Suspendisse ullamcorper, mi vel molestie ornare, arcu magna euismod ipsum, in
                            malesuada nulla magna ut enim. Morbi lacinia magna sed sapien auctor, vitae luctus nunc cursus.
                        </p>                            
                    </div>                    
                </div>
            </div>
            <div class="row tm-row tm-mb-120">
                <div class="col-lg-4 tm-about-col">
                    <div class="tm-bg-gray tm-about-pad">
                        <div class="text-center tm-mt-40 tm-mb-60">
                            <i class="fas fa-bezier-curve fa-4x tm-color-primary"></i>                            
                        </div>                        
                        <h2 class="mb-3 tm-color-primary tm-post-title">Background</h2>
                        <p class="mb-0 tm-line-height-short">
                            Phasellus pulvinar nisl ornare leo porttitor, et vestibulum lorem semper. 
                            Duis risus ex, molestie sit amet magna in,
                            pharetra pellentesque est. Curabitur elit metus.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4 tm-about-col">
                    <div class="tm-bg-gray tm-about-pad">
                        <div class="text-center tm-mt-40 tm-mb-60">
                            <i class="fas fa-users-cog fa-4x tm-color-primary"></i>                            
                        </div>                        
                        <h2 class="mb-3 tm-color-primary tm-post-title">Teamwork</h2>
                        <p class="mb-0 tm-line-height-short">
                            Suspendisse ullamcorper, mi vel molestie ornare, arcu magna euismod ipsum, in malesuada nulla magna ut enim. 
                            Morbi lacinia magna sed auctor, vitae nunc cursus.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4 tm-about-col">
                    <div class="tm-bg-gray tm-about-pad">
                        <div class="text-center tm-mt-40 tm-mb-60">
                            <i class="fab fa-creative-commons-sampling fa-4x tm-color-primary"></i>                            
                        </div>                        
                        <h2 class="mb-3 tm-color-primary tm-post-title">Our Core Value</h2>
                        <p class="mb-0 tm-line-height-short">
                            Nunc mi ante, suscipit vel dapibus et, volutpat sit amet ante. In tempor nec sem vitae varius. Aliquam tincidunt orci sem, et imperdiet massa consectetur nec.
                        </p>
                    </div>
                </div>
            </div>            
            <div class="row tm-row tm-mb-60">
                <div class="col-12">
                    <hr class="tm-hr-primary  tm-mb-55">
                </div>                
                <div class="col-lg-6 tm-mb-60 tm-person-col">
                    <div class="media tm-person">
                        <img src="img/about-02.jpg" alt="Image" class="img-fluid mr-4">
                        <div class="media-body">
                            <h2 class="tm-color-primary tm-post-title mb-2">John Henry</h2>
                            <h3 class="tm-h3 mb-3">CEO/Founder</h3>
                            <p class="mb-0 tm-line-height-short">
                                Aliquam non vulputate lectus, vel ultricies diam. Suspendisse at ipsum
                                hendrerit, vestibulum mi id, mattis tortor.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 tm-mb-60 tm-person-col">
                    <div class="media tm-person">
                        <img src="img/about-03.jpg" alt="Image" class="img-fluid mr-4">
                        <div class="media-body">
                            <h2 class="tm-color-primary tm-post-title mb-2">Timy Cake</h2>
                            <h3 class="tm-h3 mb-3">Project Director</h3>
                            <p class="mb-0 tm-line-height-short">
                                Quisque in bibendum elit, in egestas turpis. Vestibulum ornare sollicitudin congue. 
                                Aliquam lorem mi, maximus at iaculis ut.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 tm-mb-60 tm-person-col">
                    <div class="media tm-person">
                        <img src="img/about-04.jpg" alt="Image" class="img-fluid mr-4">
                        <div class="media-body">
                            <h2 class="tm-color-primary tm-post-title mb-2">Jay Zoona</h2>
                            <h3 class="tm-h3 mb-3">Supervisor</h3>
                            <p class="mb-0 tm-line-height-short">
                                Maecenas eu mi eu dui cursus consequat non eu metus. Morbi ac
                                turpis eleifend, commodo purus eget, commodo mauris.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 tm-mb-60 tm-person-col">
                    <div class="media tm-person">
                        <img src="img/about-05.jpg" alt="Image" class="img-fluid mr-4">
                        <div class="media-body">
                            <h2 class="tm-color-primary tm-post-title mb-2">Catherine Soft</h2>
                            <h3 class="tm-h3 mb-3">Team Leader</h3>
                            <p class="mb-0 tm-line-height-short">
                                Integer eu sapien hendrerit,
                                imperdiet arcu sit amet, sollicitudin ipsum.
                                Phasellus consequat suscipit ligula eget bibendum.
                            </p>
                        </div>
                    </div>
                </div>
            </div>        
            <footer class="row tm-row">
                <div class="col-md-6 col-12 tm-color-gray">
                    Design: <a rel="nofollow" target="_parent" href="https://templatemo.com" class="tm-external-link">TemplateMo</a>
                </div>
                <div class="col-md-6 col-12 tm-color-gray tm-copyright">
                    Copyright 2020 Xtra Blog Company Co. Ltd.
                </div>
            </footer>
        </main>
    </div>
    <script src="js/jquery.min.js"></script>
    <script src="js/templatemo-script.js"></script>
</body>
</html>

templates/base.html
{% load  static  %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Project site</title>
	<link rel="stylesheet" href="{%static "fontawesome/css/all.min.css "%}"> <!-- https://fontawesome.com/ -->
	<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"> <!-- https://fonts.google.com/ -->
    <link href="{%static "css/bootstrap.min.css "%}" rel="stylesheet">
    <link href="{%static "css/templatemo-xtra-blog.css" %}" rel="stylesheet">
<!--
    
TemplateMo 553 Xtra Blog

https://templatemo.com/tm-553-xtra-blog

-->
</head>
<body>
    <header class="tm-header" id="tm-header">
        <div class="tm-header-wrapper">
            <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="tm-site-header">
                <div class="mb-3 mx-auto tm-site-logo"><i class="fas fa-times fa-2x"></i></div>            
                <h1 class="text-center">project site</h1>
            </div>
            <nav class="tm-nav" id="tm-nav">            
                <ul>
                    {% if request.user.is_authenticated %}
                    <li class="tm-nav-item"> 
                        <a class="tm-nav-link" > 
                            {{ request.user}} 
                   </a>
                       <li class="tm-nav-item">
                           <a href="{% url 'users:logout' %}" class="nav-link btn btn-danger text-withe" >Log out</a>
                        </li>
                        {% else %}
                        <li class="tm-nav-item">
                            <a href="{% url 'users:login' %}" class="nav-link btn btn-success text-withe" >Log in</a>
                   </ul>
               </li>
                    {% endif %}
                    <li class="tm-nav-item active"><a href="{% url 'project:home' %}" class="tm-nav-link">
                        <i class="fas fa-home"></i>
                        Home
                    </a></li>
                    <li class="tm-nav-item"><a href="post.html" class="tm-nav-link">
                        <i class="fas fa-pen"></i>
                        Single Post
                    </a></li>
                    <li class="tm-nav-item"><a href="about.html" class="tm-nav-link">
                        <i class="fas fa-users"></i>
                        About Xtra
                    </a></li>
                </ul>
            </nav>
            <div class="tm-mb-65">
                <a rel="nofollow" href="https://fb.com/templatemo" class="tm-social-link">
                    <i class="fab fa-facebook tm-social-icon"></i>
                </a>
                <a href="https://twitter.com" class="tm-social-link">
                    <i class="fab fa-twitter tm-social-icon"></i>
                </a>
                <a href="https://instagram.com" class="tm-social-link">
                    <i class="fab fa-instagram tm-social-icon"></i>
                </a>
                <a href="https://linkedin.com" class="tm-social-link">
                    <i class="fab fa-linkedin tm-social-icon"></i>
                </a>
            </div>
            <p class="tm-mb-80 pr-5 text-white">
                Xtra Blog is a multi-purpose HTML template from TemplateMo website. Left side is a sticky menu bar. Right side content will scroll up and down.
            </p>
        </div>
    </header>
    {% block content %}{% endblock content %}
    <footer class="row tm-row">
        <hr class="col-12">
        <div class="col-md-6 col-12 tm-color-gray">
            Design: <a rel="nofollow" target="_parent" href="https://templatemo.com" class="tm-external-link">TemplateMo</a>
        </div>
        <div class="col-md-6 col-12 tm-color-gray tm-copyright">
            Copyright 2020 Xtra Blog Company Co. Ltd.
        </div>
    </footer>
 <script src="{% static 'js/jquery.min.js' %}"></script>
 <script src="{% static 'js/templatemo-script.js' %}"></script> 

</body>

</html>

templates/post.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <main class="tm-main">
        <!-- Search form -->
        <div class="row tm-row">
            <div class="col-12">
                <form method="GET" class="form-inline tm-mb-80 tm-search-form">                
                    <input class="form-control tm-search-input" name="query" type="text" placeholder="Search..." aria-label="Search">
                    <button class="tm-search-button" type="submit">
                        <i class="fas fa-search tm-search-icon" aria-hidden="true"></i>
                    </button>                                
                </form>
            </div>                
        </div>            
        <div class="row tm-row">
            <div class="col-12">
                <hr class="tm-hr-primary tm-mb-55">
                <!-- Video player 1422x800 -->
                <video width="954" height="535" controls class="tm-mb-40">
                    <source src="video/wheat-field.mp4" type="video/mp4">							  
                    Your browser does not support the video tag.
                </video>
            </div>
        </div>
        <div class="row tm-row">
            <div class="col-lg-8 tm-post-col">
                <div class="tm-post-full">                    
                    <div class="mb-4">
                        <h2 class="pt-2 tm-color-primary tm-post-title">{{ post.title }}</h2>
                        <p class="tm-mb-40">{{ post.created_at}} {{ post.user.username}}</p>
                        <p> {{ post.body }}
                        </p>
                        <span class="d-block text-right tm-color-primary">{{ post.category }}</span>
                    </div>
                    
                    <!-- Comments -->
                    <div>
                        <h2> {{ comment | length }} Comments</h2>
                        {% for comment in comments  %}
                        <hr class="tm-hr-primary tm-mb-45">
                        <div class="tm-comment tm-mb-45">
                            <figure class="tm-comment-figure">
                                <img src="{{comment.user.avatar.url}}" alt="" >
                                <figcaption class="tm-color-primary text-center">{{comment.user.username}} </figcaption>
                            </figure>
                            <div>
                                <p>
                                    {{comment.body}}
                                </p>
                                <div class="d-flex justify-content-between">
                                    <a href="#" class="tm-color-primary">REPLY</a>
                                    <span class="tm-color-primary">{{comment.created_at}}</span>
                                </div>                                                 
                            </div>                                
                        </div>
                        {% endfor %}
                        <div class="tm-comment-reply tm-mb-45">
                            <hr>
                            <div class="tm-comment">
                                <figure class="tm-comment-figure">
                                    <img src="img/comment-2.jpg" alt="Image" class="mb-2 rounded-circle img-thumbnail">
                                    <figcaption class="tm-color-primary text-center">Jewel Soft</figcaption>    
                                </figure>
                                <p>
                                    Nunc et eros quis enim feugiat tincidunt et vitae dui.
                                    Nullam consectetur justo ac ex laoreet rhoncus. Nunc
                                    id leo pretium, faucibus sapien vel, euismod turpis.
                                </p>
                            </div>                                
                            <span class="d-block text-right tm-color-primary">June 21, 2020</span>
                        </div>
                        <form action="{% url 'project:comment-create' %}" class="mb-5 tm-comment-form">
                            <h2 class="tm-color-primary tm-post-title mb-4">Your comment</h2>
                            <div class="mb-4">
                                
                                <textarea class="form-control" name="message" rows="6"></textarea>
                            </div>
                            <div class="text-right">
                                <button class="tm-btn tm-btn-primary tm-btn-small">Submit</button>                        
                            </div>                                
                        </form>                          
                    </div>
                </div>
            </div>
            <aside class="col-lg-4 tm-aside-col">
                <div class="tm-post-sidebar">
                    <hr class="mb-3 tm-hr-primary">
                    <h2 class="mb-4 tm-post-title tm-color-primary">Categories</h2>
                    <ul class="tm-mb-75 pl-5 tm-category-list">
                        <li><a href="#" class="tm-color-primary">Visual Designs</a></li>
                        <li><a href="#" class="tm-color-primary">Travel Events</a></li>
                        <li><a href="#" class="tm-color-primary">Web Development</a></li>
                        <li><a href="#" class="tm-color-primary">Video and Audio</a></li>
                        <li><a href="#" class="tm-color-primary">Etiam auctor ac arcu</a></li>
                        <li><a href="#" class="tm-color-primary">Sed im justo diam</a></li>
                    </ul>
                    <hr class="mb-3 tm-hr-primary">
                    <h2 class="tm-mb-40 tm-post-title tm-color-primary">Related Posts</h2>
                    <a href="#" class="d-block tm-mb-40">
                        <figure>
                            <img src="img/img-02.jpg" alt="Image" class="mb-3 img-fluid">
                            <figcaption class="tm-color-primary">Duis mollis diam nec ex viverra scelerisque a sit</figcaption>
                        </figure>
                    </a>
                    <a href="#" class="d-block tm-mb-40">
                        <figure>
                            <img src="img/img-05.jpg" alt="Image" class="mb-3 img-fluid">
                            <figcaption class="tm-color-primary">Integer quis lectus eget justo ullamcorper ullamcorper</figcaption>
                        </figure>
                    </a>
                    <a href="#" class="d-block tm-mb-40">
                        <figure>
                            <img src="img/img-06.jpg" alt="Image" class="mb-3 img-fluid">
                            <figcaption class="tm-color-primary">Nam lobortis nunc sed faucibus commodo</figcaption>
                        </figure>
                    </a>
                </div>                    
            </aside>
        </div>


{% endblock content %}
	
    
            